language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
  - 7

before_script:
  - composer install --prefer-dist --dev

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 -p src/ tests/

matrix:
  allow_failures:
    - php: hhvm
    - php: 7

  fast_finish: true
