language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 --warning-severity=6 --encoding=utf-8 -p src/ tests/
