sudo: false

language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

before_script:
  - composer install --prefer-dist -n

script:
  - composer validate
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 -p src/ tests/
