name: Klein

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0, 8.1]

    name: PHP ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Install Dependencies
        run: composer update

      - name: Run phpunit tests
        run: |
          ./vendor/bin/phpunit

      - name: Run phpcs
        run: ./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 -p src/ tests/